services:
  # Frontend (Next.js)
  - type: web
    name: procontel-frontend
    env: node
    buildCommand: npm run install-all && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://procontel-frontend.onrender.com
      - key: BACKEND_URL
        value: https://procontel-backend.onrender.com 